type Registro = (String, String, String, String, String, String, Int, Int, String)
type Base = [Registro]

-- Encabezado: "nombre", "provincia", "departamento", "localidad", "direccion", "web", "pantallas", "butacas", "tipo_de_gestion"

base :: Base
base = [("Cine Teatro Español", "Buenos Aires", "25 de mayo", "25 de mayo", "Calle 9 entre 29 Y 30", "https://www.instagram.com/teatro_espanol/", 1, 500, "Pública"),
        ("Cine Santa Rosa De Lima", "Buenos Aires", "Trenque Lauquen", "30 de agosto", "Santa Rosa De Lima 170", "https://www.trenquelauquen.gov.ar", 1, 410, "Pública"),
        ("Tu Cine 9 de Julio", "Buenos Aires", "9 de julio", "9 de julio", "Robbio 840", "http://9dejulio.tucine.com.ar/", 1, 165, "Privada"),
        ("Cinema Adrogue", "Buenos Aires", "Almirante Brown", "Adrogué", "Hipolito Yrigoyen 13200", "https://www.cinemaadrogue.com/", 10, 2505, "Privada"),
        ("CPM Paseo Adrogue", "Buenos Aires", "Almirante Brown", "Adrogué", "Segui 699", "https://cpmcines.com/", 4, 710, "Privada"),
        ("Cinemark Alto Avellaneda", "Buenos Aires", "Avellaneda", "Avellaneda", "Guemes 897", "https://www.cinemarkhoyts.com.ar/", 6, 1275, "Privada"),
        ("Cinepolis Avellaneda", "Buenos Aires", "Avellaneda", "Avellaneda", "Autopista Bs. As. - La Plata Km 6", "https://www.cinepolis.com.ar/", 16, 3485, "Privada"),
        ("Flix Cinema", "Buenos Aires", "Azul", "Azul", "Bolivar 416", "http://azul.flixcinema.com.ar/", 1, 160, "Privada"),
        ("Cine Vision", "Buenos Aires", "Bahía Blanca", "Bahía Blanca", "Belgrano 153", "https://www.cinesdelcentrobb.com.ar/", 3, 907, "Privada"),
        ("Cine Visual", "Buenos Aires", "Bahía Blanca", "Bahía Blanca", "Chiclana 452", "http://www.cinesdelcentrobb.com.ar/", 2, 501, "Privada"),
        ("Cinemacenter Bahia Blanca", "Buenos Aires", "Bahía Blanca", "Bahía Blanca", "Av. Sarmiento 2153", "http://www.cinemacenter.com.ar/", 7, 1501, "Privada"),
        ("Cine Paris 2D Balcarce", "Buenos Aires", "Balcarce", "Balcarce", "Calle 18 684", "https://www.facebook.com/CineParisBalcarce/", 1, 272, "Privada"),
        ("Centro Cultural Atilio Marinelli", "Buenos Aires", "Benito Juarez", "Benito Juarez", "Otamendi y Av. San Martin", "Facebook: Centro Cultural Atilio Marinelli de Benito Juárez", 1, 350, "Pública"),
        ("Cine Avenida", "Buenos Aires", "Bolivar", "Bolivar", "Av. San Martin 642", "https://www.facebook.com/cineavenidabolivar/", 1, 256, "Privada"),
        ("Cinemark Soleil", "Buenos Aires", "San Isidro", "Boulogne", "Bernardo De Yrigoyen 2647", "https://www.cinemarkhoyts.com.ar", 6, 1895, "Privada"),
        ("Centro Cultural Florencio Constantino", "Buenos Aires", "Bragado", "Bragado", "Belgrano 1260", "", 1, 750, "Pública"),
        ("Cine Teatro Paramount", "Buenos Aires", "Tres de Febrero", "Caseros", "Tres De Febrero 2561", "https://www.tresdefebrero.gov.ar/tema/cine-teatro-paramount/", 2, 645, "Pública"),
        ("Cine Teatro Avenida", "Buenos Aires", "Castelli", "Castelli", "Av. 25 De Mayo 540", "Facebook: Cine Teatro Avenida", 1, 254, "Pública"),
        ("Cine Teatro Español", "Buenos Aires", "Chacabuco", "Chacabuco", "Pueyrredón 29", "http://cinemachacabuco.com.ar/", 1, 700, "Privada"),
        ("Teatro Italiano Espacio INCAA", "Buenos Aires", "Chacabuco", "Chacabuco", "Av. Alsina 29", "Facebook: Teatro Italiano - Galería de Arte", 1, 289, "Pública"),
        ("Cine Español Chivilcoy", "Buenos Aires", "Chivilcoy", "Chivilcoy", "Av. Soarez 86", "https://www.facebook.com/cinechivilcoy/", 1, 500, "Privada"),
        ("Metropol", "Buenos Aires", "Chivilcoy", "Chivilcoy", "Av. Ceballos 29", "https://www.facebook.com/CineMetropolChivilcoy/", 1, 500, "Privada"),
        ("Tu Cine Chivilcoy", "Buenos Aires", "Chivilcoy", "Chivilcoy", "Pellegrini 225", "http://chivilcoy.tucine.com.ar/", 2, 348, "Privada"),
        ("Nuevo Ciudadela", "Buenos Aires", "Tres de Febrero", "Ciudadela", "Av. Maipu 3927", "", 2, 350, "Privada"),
        ("Cine Teatro Colon", "Buenos Aires", "Colón", "Colón", "Calle 48 Y 19", "http://cineteatrocolon.com.ar", 1, 270, "Privada"),
        ("Cine Teatro Helios", "Buenos Aires", "Morón", "El Palomar", "Boulevard San Martin 3076", "", 1, 349, "Privada"),
        ("Canning Multiplex", "Buenos Aires", "Ezeiza", "Ezeiza", "Formosa 653", "https://www.multiplex.com.ar/", 6, 1132, "Privada"),
        ("Cinemacenter Florencio Varela", "Buenos Aires", "Florencio Varela", "Florencio Varela", "Av. San Martin 554", "http://www.cinemacenter.com.ar/", 6, 1327, "Privada"),
        ("Cine Teatro Español", "Buenos Aires", "General Belgrano", "General Belgrano", "Larrea 688", "", 1, 378, "Pública"),
        ("Espacio INCAA Gral Madariaga", "Buenos Aires", "General Juan Madariaga", "General Madariaga", "Dr. Carlos Madariaga 499", "", 1, 230, "Pública"),
        ("CPM Catan", "Buenos Aires", "La Matanza", "Gonzalez Catán", "Ruta 3 Km 29 Bj Manuel De Rosas 14457", "https://cpmcines.com", 6, 1114, "Privada"),
        ("Showcase Cinemas Haedo", "Buenos Aires", "Morón", "Haedo", "Dr. Luis Guemes 393", "https://www.todoshowcase.com/", 14, 3890, "Privada"),
        ("Tu Cine Junin", "Buenos Aires", "Junín", "Junín", "Jorge Newbery 263", "http://www.tucine.com.ar", 3, 453, "Privada"),
        ("Cine Municipal Ecoselect", "Buenos Aires", "La Plata", "La Plata", "19 Y 51", "http://www.cultura.laplata.gov.ar", 1, 60, "Pública"),
        ("Cine Municipal Select", "Buenos Aires", "La Plata", "La Plata", "Calle 50 entre 6 y 7", "http://www.cultura.laplata.gov.ar/lugar/cine-municipal-select", 1, 174, "Pública"),
        ("Cinema 8", "Buenos Aires", "La Plata", "La Plata", "Calle 8 981", "http://www.cinemalaplata.com/", 3, 1084, "Privada"),
        ("Cinema City", "Buenos Aires", "La Plata", "La Plata", "Calle 50 723", "http://www.cinemalaplata.com/", 3, 640, "Privada"),
        ("Cinema Paradiso", "Buenos Aires", "La Plata", "La Plata", "Calle 46 780", "http://www.cinemalaplata.com", 4, 603, "Privada"),
        ("Cinema Rocha", "Buenos Aires", "La Plata", "La Plata", "Calle 49 621", "http://www.cinemalaplata.com", 6, 1613, "Privada"),
        ("Cinema San Martin", "Buenos Aires", "La Plata", "La Plata", "Calle 7 923", "http://www.cinemalaplata.com", 7, 2184, "Privada"),
        ("Coto Lanus", "Buenos Aires", "Lanús", "Lanús", "Warnes 2450", "https://www.zonacines.com.ar", 8, 2037, "Privada"),
        ("San Martin", "Buenos Aires", "Las Flores", "Las Flores", "San Martin 593", "http://www.cinesanmartin3d.com.ar/", 1, 0 , "Privada"),
        ("Las Toninas", "Buenos Aires", "La Costa", "Las Toninas", "Calle 7 1564 Entre 36 Y 38", "", 1, 245, "Privada"),
        ("Cine Club Jorge Newbery", "Buenos Aires", "Lincoln", "Lincoln", "Av. Massey 839", "https://www.facebook.com/clubjorgenewberylincoln/", 1, 483, "Privada"),
        ("Cine Teatro Italiano", "Buenos Aires", "Lobos", "Lobos", "9 De julio 0142", "https://www.facebook.com/teatrocineitaliano/", 1, 350, "Pública"),
        ("Cinemark Malvinas Argentinas", "Buenos Aires", "Malvinas Argentinas", "Los Polvorines", "Av. Illia 3770", "https://www.cinemarkhoyts.com.ar", 10, 2414, "Privada"),
        ("Leonardo Favio", "Buenos Aires", "General Viamonte", "Los Toldos", "Mitre 841", "", 1, 330, "Privada"),
        ("Cinepolis Luján", "Buenos Aires", "Luján", "Luján", "R. Payró y Mario Bravo", "https://www.cinepolis.com.ar/", 6, 1182, "Privada"),
        ("Cinema Rosso", "Buenos Aires", "Luján", "Luján", "Lavalle 410", "www.cinemarossolujan.com/", 2, 197, "Privada"),
        ("Cine Teatro Sociedad Italiana", "Buenos Aires", "Maipú", "Maipú", "Rivadavia 555", "https://www.facebook.com/CineTeatroSociedadItalianaMaipu", 1, 450, "Privada"),
        ("Atlantica California", "Buenos Aires", "La Costa", "Mar de Ajó", "Hipolito Irigoyen 18", "https://www.facebook.com/cinecaliforniamardeajo/", 2, 551, "Privada"),
        ("Ambassador", "Buenos Aires", "General Pueyrredon", "Mar del Plata", "Cordoba 1673", "http://www.cinemacenter.com.ar/", 4, 947, "Privada"),
        ("Cine Cristal", "Buenos Aires", "General Pueyrredon", "Mar del Plata", "Entre Rios 1783", "", 2, 40, "Privada"),
        ("Cines Paseo Aldrey", "Buenos Aires", "General Pueyrredon", "Mar del Plata", "Alberti 1610", "http://www.cinemacenter.com.ar/", 6, 1121, "Privada"),
        ("Herodes", "Buenos Aires", "General Pueyrredon", "Mar del Plata", "Belgrano 2327", "", 2, 120, "Privada"),
        ("Paseo Diagonal", "Buenos Aires", "General Pueyrredon", "Mar del Plata", "Belgrano Y Diag. Pueyrredon 3058", "", 4, 687, "Privada"),
        ("T.E.Y.C.I. Cinema", "Buenos Aires", "General Pueyrredon", "Mar del Plata", "Rivadavia 3050", "http://www.cinemacenter.com.ar/", 2, 487, "Privada"),
        ("Teatro Auditorium", "Buenos Aires", "General Pueyrredon", "Mar del Plata", "Bv. Maritimo 2280", "http://programacionauditorium.blogspot.com/", 3, 1563, "Pública"),
        ("Hoyts Unicenter", "Buenos Aires", "San Isidro", "Martínez", "Parana 3745", "https://www.cinemarkhoyts.com.ar/", 16, 3427, "Privada"),
        ("Cine Mercedes", "Buenos Aires", "Mercedes", "Mercedes", "Calle 20 728", "http://cinemercedes.com/", 1, 190, "Privada"),
        ("Cine Atlantico", "Buenos Aires", "General Alvarado", "Miramar", "Calle 21 1564", "http://www.cineteatroatlantico.com.ar/", 1, 902, "Privada"),
        ("Hoyts Moreno", "Buenos Aires", "Moreno", "Moreno", "Av. Victorica 1128", "https://www.cinemarkhoyts.com.ar/", 10, 2476, "Privada"),
        ("Hoyts Moron", "Buenos Aires", "Morón", "Morón", "Juan Manuel De Rosas 658", "https://www.cinemarkhoyts.com.ar/", 8, 1865, "Privada"),
        ("T. Municipalidad G. De La Ferrere", "Buenos Aires", "Morón", "Morón", "Alte. Brown 990", "http://www.moron.gob.ar", 1, 133, "Pública"),
        ("Lumiton", "Buenos Aires", "Vicente López", "Munro", "Sargento Cabral 2354", "https://lumiton.ar/", 1, 30, "Pública"),
        ("Showcase Norte", "Buenos Aires", "Vicente López", "Munro", "E. Echeverria 3750", "https://www.todoshowcase.com/", 17, 4214, "Privada"),
        ("Cine Ocean", "Buenos Aires", "Necochea", "Necochea", "Calle 83 350", "https://www.cinesocean.com.ar/", 3, 1620, "Privada"),
        ("Cine Paris", "Buenos Aires", "Olavarría", "Olavarría", "General Paz 2720", "http://www.cineparis.com.ar", 2, 383, "Privada"),
        ("Flix Olavarria", "Buenos Aires", "Olavarría", "Olavarría", "Rivadavia 4730", "http://olavarria.flixcinema.com.ar/", 2, 660, "Privada"),
        ("Centro Cultural York", "Buenos Aires", "Vicente López", "Olivos", "Juan Bautista Alberdi 895", "https://www.facebook.com/cineteatroyorkolivos", 1, 280, "Pública"),
        ("Cinema Pergamino", "Buenos Aires", "Pergamino", "Pergamino", "Av. Mayo y San Nicolas", "http://vamosacinema.com/", 2, 556, "Privada"),
        ("Cine Teatro Municipal Pila Padre Adolfo Anastasio", "Buenos Aires", "Pila", "Pila", "Calle 6 y Calle 19", "https://www.facebook.com/CineTeatroPila/", 1, 178, "Pública"),
        ("Cinepolis Pilar", "Buenos Aires", "Pilar", "Pilar", "Panamericana Ac. Norte Km 50", "https://www.villagecines.com/", 9, 2675, "Privada"),
        ("Palmas Multiplex", "Buenos Aires", "Pilar", "Pilar", "Las Magnolias 754", "https://www.multiplex.com.ar/", 9, 1407, "Privada"),
        ("Atlantica Oasis", "Buenos Aires", "Pinamar", "Pinamar", "Av. Shaw 644", "http://www.cineoasis.com.ar/", 2, 744, "Privada"),
        ("Cinema Colon", "Buenos Aires", "Coronel de Marina L. Rosales", "Punta Alta", "Rivadavia 459", "http://www.cinemacolon.com.ar", 1, 390, "Privada"),
        ("Cine Teatro Municipalidad De Quilmes", "Buenos Aires", "Quilmes", "Quilmes", "Mitre 721", "https://www.facebook.com/INCAAQuilmes/", 1, 415, "Pública"),
        ("Hoyts General Cinema Quilmes", "Buenos Aires", "Quilmes", "Quilmes", "Av. Calchaqui 3950", "https://www.cinemarkhoyts.com.ar/", 12, 2580, "Privada"),
        ("Showcase Quilmes", "Buenos Aires", "Quilmes", "Quilmes", "Olavarria 180", "https://www.todoshowcase.com/", 8, 1730, "Privada"),
        ("Atlas Nordelta", "Buenos Aires", "Tigre", "Rincón de Milberg", "Av. De Los Lagos 7010", "http://www.nordeltacc.com.ar/", 5, 969, "Privada"),
        ("Cine Frances", "Buenos Aires", "Rojas", "Rojas", "Bartolomé Mitre 328", "https://www.facebook.com/CineFrancesRojas/", 1, 230, "Privada"),
        ("Cine Teatro Soc. Italiana", "Buenos Aires", "Salliqueló", "Salliqueló", "Pueyrredón 77", "Facebook: Cine Salliqueló - Sociedad Italiana", 1, 420, "Privada"),
        ("Cervantes", "Buenos Aires", "Salto", "Salto", "Alvear 65", "", 1, 220, "Privada"),
        ("Cinepolis Merlo", "Buenos Aires", "Merlo", "San Antonio de Padua", "Av. Juan Domingo Peron 24056", "https://www.villagecines.com/", 6, 1315, "Privada"),
        ("Atlantica Arenas", "Buenos Aires", "La Costa", "San Bernardo", "Chiozza 1776", "", 3, 1358, "Privada"),
        ("Gran Tuyu", "Buenos Aires", "La Costa", "San Clemente", "Av. San Martin 181", "https://www.facebook.com/cine.tuyu/", 1, 450, "Privada"),
        ("Cinemark San Justo", "Buenos Aires", "La Matanza", "San Justo", "Av. Juan Manuel De Rosas 3990", "https://www.cinemarkhoyts.com.ar", 6, 1843, "Privada"),
        ("La Palma", "Buenos Aires", "San Pedro", "San Pedro", "Belgrano 961", "https://www.facebook.com/MEC.LaPalma/", 2, 471, "Privada"),
        ("Atlantica Yanel", "Buenos Aires", "La Costa", "Santa Teresita", "Calle 32 372", "", 2, 635, "Privada"),
        ("Atlantico", "Buenos Aires", "La Costa", "Santa Teresita", "Calle 41 258", "", 1, 1107, "Privada"),
        ("Cinemacenter Tandil", "Buenos Aires", "Tandil", "Tandil", "Panama 351", "http://www.cinemacenter.com.ar/", 4, 758, "Privada"),
        ("Espacio INCAA Unicen", "Buenos Aires", "Tandil", "Tandil", "Yrigoyen 662", "", 1, 430, "Pública"),
        ("Centro Cultural Municipal Dr. Ricardo Romera", "Buenos Aires", "Tapalque", "Tapalque", "Av. 9 De Julio Y Av. San Martin", "", 1, 264, "Pública"),
        ("Hoyts Temperley", "Buenos Aires", "Lomas de Zamora", "Temperley", "Av. Hipolito Irigoyen 10699", "https://www.cinemarkhoyts.com.ar/", 9, 2382, "Privada"),
        ("Cinemark Tortuguitas", "Buenos Aires", "Malvinas Argentinas", "Tortuguitas", "Constituyentes Y Au. Panamericana Km 36.5", "https://www.cinemarkhoyts.com.ar", 8, 1905, "Privada"),
        ("Cine Barrio Alegre", "Buenos Aires", "Trenque Lauquen", "Trenque Lauquen", "9 De julio 0133", "https://www.facebook.com/cinebarrio3d/", 1, 1200, "Privada"),
        ("Cine Teatro Español", "Buenos Aires", "Tres Lomas", "Tres Lomas", "Monteverde 257", "https://www.facebook.com/cinetreslomas/", 1, 300, "Privada"),
        ("Cine Teatro Jose Hernandez", "Buenos Aires", "General San Martin", "Villa Ballester", "Balcarce 2973", "Facebook: Cine - Teatro José Hernández", 1, 660, "Privada"),
        ("Victor Show Cinemas", "Buenos Aires", "Tres de Febrero", "Villa Bosch", "El Payador 5539", "https://www.facebook.com/VictorShowCinemas/", 3, 413, "Privada"),
        ("Atlantic", "Buenos Aires", "Villa Gesell", "Villa Gesell", "Paseo 105 Entre 3 Y 2", "http://cineatlantic.com.ar/", 1, 400, "Privada"),
        ("Cine Teatro Coliseo", "Buenos Aires", "Zarate", "Zarate", "19 De marzo 0314", "https://es-la.facebook.com/ZarateCineTeatroColiseo/", 1, 300, "Privada"),
        ("Cinemacenter Catamarca", "Catamarca", "Capital", "Catamarca", "Av. Guemes 850", "http://www.cinemacenter.com.ar/", 5, 914, "Privada"),
        ("Cines Del Solar", "Catamarca", "Capital", "Catamarca", "Intendente Mamerto Medina 220", "http://www.cinemacenter.com.ar/", 5, 743, "Privada"),
        ("Cinemacenter Avalos", "Chaco", "San Fernando", "Resistencia", "Av. Avalos y Av. Lavalle", "http://www.cinemacenter.com.ar/", 5, 792, "Privada"),
        ("Cinemacenter Resistencia", "Chaco", "San Fernando", "Resistencia", "Av. Dr. Sabin y Av. Nicolas Avellaneda", "http://www.cinemacenter.com.ar/", 3, 690, "Privada"),
        ("Los Cines De La Costa - Sarmiento", "Chaco", "San Fernando", "Resistencia", "Av. Sarmiento 2600", "http://resistencia.loscinesdelacosta.com.ar/", 5, 820, "Privada"),
        ("Cine Coliseo", "Chubut", "Escalante", "Comodoro Rivadavia", "San Martin 570", "http://www.cinecr.com.ar", 1, 380, "Privada"),
        ("Cine Teatro Español", "Chubut", "Escalante", "Comodoro Rivadavia", "San Martin 668", "http://www.cinecr.com.ar", 1, 463, "Privada"),
        ("Auditorio Municipal De Esquel", "Chubut", "Futaleufu", "Esquel", "Belgrano 330", "https://www.facebook.com/CulturaEsquel/", 1, 243, "Pública"),
        ("Sociedad Italiana - Auditorium Puerto Madryn", "Chubut", "Biedma", "Puerto Madryn", "28 De julio 0129", "http://www.cinemadryn.com/", 2, 486, "Privada"),
        ("Centro Cultural Jose Hernandez", "Chubut", "Rawson", "Rawson", "Dr. Jorge Galina S/N y Mitre", "", 1, 400, "Privada"),
        ("Coliseo", "Chubut", "Rawson", "Trelew", "Belgrano 375", "", 1, 380, "Privada"),
        ("Espacio INCAA Km 1460", "Chubut", "Rawson", "Trelew", "9 De julio 0655", "Facebook: Espacio INCAA Trelew", 1, 100, "Pública"),
        ("Salon Municipal de Cine", "Chubut", "Futaleufu", "Trevelin", "28 De julio 0414", "", 1, 150, "Pública"),
        ("Angeba", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Lavalle 750", "", 4, 100, "Privada"),
        ("Arte Multiplex", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Cabildo 2829", "https://www.multiplex.com.ar/", 5, 792, "Privada"),
        ("Atlas Caballito", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Rivadavia 5071", "https://www.villagecines.com/", 9, 1769, "Privada"),
        ("Atlas La Rural", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Juncal 4431", "www.atlascines.com", 1, 130, "Privada"),
        ("Atlas Liniers", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Ramón L. Falcón 7115", "www.atlascines.com", 4, 460, "Privada"),
        ("Atlas Paseo Alcorta", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Jeronimo Salguero 3172", "cineatlasweb.com.ar", 3, 432, "Privada"),
        ("Atlas Patio Bullrich", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Posadas 1245", "cineatlasweb.com.ar", 3, 585, "Privada"),
        ("Atlas Rivera Indarte", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Rivera Indarte 44", "cineatlasweb.com.ar", 5, 1263, "Privada"),
        ("Belgrano Multiplex", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Vuelta De Obligado 2238", "https://www.multiplex.com.ar/", 8, 2314, "Privada"),
        ("Centro Cultural San Martín Sala 1 y 2", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Sarmiento 1551", "https://elculturalsanmartin.ar/cine/", 2, 192, "Pública"),
        ("Cine Amigos Del Bellas Artes", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Pte. Figueroa Alcorta 2280", "https://www.facebook.com/amigosdelbellasartes", 1, 235, "Privada"),
        ("Cine Box", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Laprida 1423", "", 2, 40, "Privada"),
        ("Cine del Recuerdo", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Juan de Garay 1267", "", 1, 85, "Privada"),
        ("Cine Popular HQ", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Moreno 2654", "https://www.facebook.com/CulturaATENac/", 1, 158, "Privada"),
        ("Cine San Francisco", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Gral. Paz 10652", "", 1, 40, "Privada"),
        ("Cinema Devoto", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Jose Pedro Varela 4866", "https://cinemadevoto.com.ar/", 8, 1908, "Privada"),
        ("Cinemark Caballito", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. La Plata 96", "https://www.cinemarkhoyts.com.ar", 6, 898, "Privada"),
        ("Cinemark Palermo", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Beruti 3399", "https://www.cinemarkhoyts.com.ar", 10, 1738, "Privada"),
        ("Cinemark Puerto Madero", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Alicia M De Justo 1920", "https://www.cinemarkhoyts.com.ar", 8, 1379, "Privada"),
        ("Cinepolis Recoleta", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Vicente Lopez 2050", "https://www.villagecines.com/", 10, 1776, "Privada"),
        ("Complejo Cultural 25 de Mayo", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Triunvirato 4444", "https://cc25.org/", 1, 500, "Pública"),
        ("Eden - Sala 2", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Santa Fe 1825", "", 1, 30, "Privada"),
        ("El Páramo Cultural", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Carlos Calvo 3974", "https://www.facebook.com/ParamoCultural/", 1, 60, "Privada"),
        ("Gaumont", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Rivadavia 1635", "http://www.incaa.gov.ar/", 3, 1167, "Pública"),
        ("Hoyts Abasto", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Aguero 665", "https://www.cinemarkhoyts.com.ar/", 12, 3021, "Privada"),
        ("Hoyts Panamericana", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Melian 4880", "https://www.cinemarkhoyts.com.ar/", 10, 1918, "Privada"),
        ("Leopoldo Lugones", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Corrientes 1530", "https://complejoteatral.gob.ar/cine", 1, 212, "Pública"),
        ("Lorca", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Corrientes 1428", "http://cinelorca.wixsite.com/cine-lorca", 2, 452, "Privada"),
        ("Malba", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Figuero Alcorta 3415", "http://www.malba.org.ar/", 1, 224, "Privada"),
        ("Monumental Lavalle", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Lavalle 780", "https://www.multiplex.com.ar/", 7, 1270, "Privada"),
        ("Nueva Victoria", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Hipolito Yrigoyen 965", "", 2, 115, "Privada"),
        ("Popular Ecuador", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Ecuador 54", "", 1, 147, "Privada"),
        ("Raúl González Tuñón", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Corrientes 1543", "", 1, 94, "Privada"),
        ("Showcase Cinemas Belgrano", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Monroe 1655", "https://www.todoshowcase.com/", 10, 2082, "Privada"),
        ("UBA - Cosmos", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Av. Corrientes 2046", "https://www.facebook.com/pg/cinecosmos.uba/", 2, 190, "Pública"),
        ("Yrigoyen", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Hipolito Yrigoyen 945", "", 2, 64, "Privada"),
        ("Microcine Centro Cultural Recoleta", "Ciudad Autónoma de Buenos Aires", "Ciudad Autonoma de Buenos Aires", "Ciudad Autónoma de Buenos Aires", "Junin 1930", "http://www.centroculturalrecoleta.org/", 1, 100, "Pública"),
        ("Cinemacenter Alta Gracia", "Córdoba", "Santa María", "Alta Gracia", "Belgrano 466", "https://www.cinemacenter.com.ar/", 3, 431, "Privada"),
        ("Dinosaurio Mall Alta Gracia", "Córdoba", "Santa María", "Alta Gracia", "Gabino Ezeiza 1080", "https://dinomall.com.ar/", 2, 317, "Privada"),
        ("Cine Cooperativo Berrotarán", "Córdoba", "Río Cuarto", "Berrotarán", "ROGELIO MARTINEZ y MARIANO MORENO", "https://coopeb.com.ar/cine-teatro-multiespacio/", 1, 419, "Privada"),
        ("El Jardín de las Delicias", "Córdoba", "Capital", "Córdoba", "Bv. San Juan 49", "https://cineclubmunicipal.org.ar/", 1, 194, "Pública"),
        ("Cine Moderno", "Córdoba", "San Justo", "La Francia", "Antonio G. Almada 172", "https://www.facebook.com/teatrocinemoderno100/", 1, 441, "Privada"),
        ("Cinema 2000 Auditorium", "Córdoba", "San Justo", "Arroyito", "Belgrano y Rafael Nuñez", "https://www.facebook.com/pg/Cinema.2000.Arroyito.3D", 1, 207, "Privada"),
        ("Sudcinemas Bell Ville", "Córdoba", "Union", "Bell Ville", "Mitre 61", "http://sudcinemas.com.ar/cine-wp/cine/bellville/", 2, 324, "Privada"),
        ("Guillermo J. Nolter", "Córdoba", "Union", "Canals", "Moreno Y Sarmiento", "https://www.cinecoop3d.com/elcine.php", 1, 200, "Privada"),
        ("Enrique Muiño", "Córdoba", "Punilla", "Capilla del Monte", "Dean Funes 526", "", 1, 413, "Privada"),
        ("Cines Gran Rex", "Córdoba", "Capital", "Córdoba", "Av. Gral. Paz 174", "http://cinesgranrex.com.ar/", 8, 1201, "Privada"),
        ("Complejo Cinerama", "Córdoba", "Capital", "Córdoba", "Av. Colon 345", "https://www.cinerama.com.ar/", 4, 755, "Privada"),
        ("Dinosaurio Mall 60 Cuadras", "Córdoba", "Capital", "Córdoba", "Av. Circunvalacion Agustin Tosco 4552", "https://www.cinesdinomall.com.ar/", 2, 307, "Privada"),
        ("Dinosaurio Mall Alto Verde", "Córdoba", "Capital", "Córdoba", "Rodriguez Del Busto 4086", "https://www.cinesdinomall.com.ar/Inicio", 7, 1193, "Privada"),
        ("Dinosaurio Mall Ruta 20", "Córdoba", "Capital", "Córdoba", "Av. Fuerza Aerea 1700", "https://www.cinesdinomall.com.ar/Inicio", 7, 1385, "Privada"),
        ("Hoyts Nuevo Centro Cordoba", "Córdoba", "Capital", "Córdoba", "Duarte Quiros 1400", "https://www.cinemarkhoyts.com.ar/", 6, 960, "Privada"),
        ("Hoyts Patio Olmos", "Córdoba", "Capital", "Córdoba", "Av. Velez Sarsfield 361", "https://www.cinemarkhoyts.com.ar/", 8, 986, "Privada"),
        ("Showcase Cordoba", "Córdoba", "Capital", "Córdoba", "J.A. Goyechea 2851", "https://www.todoshowcase.com/", 12, 2386, "Privada"),
        ("Cine Arte Córdoba", "Córdoba", "Capital", "Córdoba", "27 De abril 0275", "https://www.facebook.com/CineArteCordoba/", 1, 210, "Privada"),
        ("Cine Aida", "Córdoba", "Cruz del Eje", "Cruz del Eje", "Thomas Edison 2126", "", 1, 444, "Privada"),
        ("Cine Teatro Coop Luz y Fuerza", "Córdoba", "Rio Cuarto", "Elena", "Mitre 31", "Facebook: Cine Teatro Cooperativo de Elena", 1, 279, "Privada"),
        ("Las Tipas Jesus Maria", "Córdoba", "Colón", "Jesús María", "Ruta Nacional 9 Esq. Corrientes", "http://www.cinesmolise.com.ar/", 3, 623, "Privada"),
        ("Las Tipas Morteros", "Córdoba", "San Justo", "Morteros", "Bv. Illia 232", "http://www.lastipasboulevard.com.ar/", 2, 300, "Privada"),
        ("Centro Cultural Leonardo Favio", "Córdoba", "Rio Cuarto", "Río Cuarto", "Buenos Aires 55", "http://www.cba.gov.ar/", 1, 219, "Pública"),
        ("Cines Del Paseo", "Córdoba", "Rio Cuarto", "Río Cuarto", "Av. Mugnaini Y Sobremonte", "http://cba.gov.ar", 4, 955, "Privada"),
        ("Strike", "Córdoba", "Tercero Arriba", "Río Tercero", "Velez Sarfield 143", "http://cinemastrike.com.ar/", 2, 400, "Privada"),
        ("Dinosaurio Mall Salsipuedes", "Córdoba", "Colón", "Salsipuedes", "Av. Sarmiento 1007", "http://www.cinesdinomall.com.ar", 2, 322, "Privada"),
        ("Las Tipas San Francisco", "Córdoba", "San Justo", "San Francisco", "Iturraspe 1448", "http://www.nuevocineradar.com.ar/", 3, 620, "Privada"),
        ("Espacio Incaa Unquillo", "Córdoba", "Colón", "Unquillo", "San Martin 1505", "http://www.unquillo.gov.ar/", 1, 220, "Pública"),
        ("Sala C.E.Y.A.L", "Córdoba", "Rio Cuarto", "Vicuña Mackenna", "Av. Carlos S. Yde 1056", "", 1, 850, "Privada"),
        ("Showcase Villa Allende", "Córdoba", "Colón", "Villa Allende", "Rio De Janeiro 1725", "https://www.todoshowcase.com/", 3, 563, "Privada"),
        ("Holiday Cines", "Córdoba", "Punilla", "Villa Carlos Paz", "9 De julio 53", "https://www.holidaycinemas.com.ar/", 4, 1000, "Privada"),
        ("Cine General Paz", "Córdoba", "Rio Segundo", "Villa del Rosario", "Sarmiento 731", "", 1, 412, "Privada"),
        ("Eter Cine", "Córdoba", "San Javier", "Villa Dolores", "Felipe Erdman 145", "http://www.etercine3d.com.ar/", 2, 400, "Privada"),
        ("Centro Cultural Leonardo Favio", "Córdoba", "General San Martin", "Villa María", "Av. Sabattini 200", "http://www.villamaria.gob.ar", 1, 200, "Pública"),
        ("Sudcinemas", "Córdoba", "General San Martin", "Villa María", "Ruta Nacional 158 Km 155,5", "http://sudcinemas.com.ar/", 4, 800, "Privada"),
        ("Sunstar Cordoba", "Córdoba", "Capital", "Villa Rivera Indarte", "Ricardo Rojas 9200", "http://www.cinesunstar.com/", 6, 1398, "Privada"),
        ("Fantasio", "Corrientes", "Bella Vista", "Bella Vista", "Salta 1059", "https://www.facebook.com/CineFantasioBellaVista/", 1, 240, "Privada"),
        ("Cinemacenter Corrientes", "Corrientes", "Capital", "Corrientes", "Av. Pedro Ferre y Chacabuco", "http://www.cinemacenter.com.ar/", 5, 1140, "Privada"),
        ("De La Costa Costanera", "Corrientes", "Capital", "Corrientes", "Carlos Pellegrini 451/311", "http://www.loscinesdelacosta.com.ar/", 2, 358, "Privada"),
        ("De La Costa Shopping", "Corrientes", "Capital", "Corrientes", "Av. Centenario 3535", "http://www.loscinesdelacosta.com.ar/", 4, 562, "Privada"),
        ("Sociedad Rural", "Corrientes", "Curuzú Cuatiá", "Curuzú Cuatiá", "Beron De Astrada 641", "http://cinedelarural.com.ar", 1, 300, "Privada"),
        ("Cines del Litoral Goya", "Corrientes", "Goya", "Goya", "España 659", "", 2, 370, "Privada"),
        ("Cine Teatro Opera", "Corrientes", "Paso de los Libres", "Paso de los Libres", "Los 108 941", "https://www.facebook.com/pg/Cineoperacorrientes/", 1, 200, "Privada"),
        ("Cine Boulevard", "Entre Ríos", "Gualeguay", "Gualeguay", "Av. Illia Y Chocho Vivanco", "Facebook: Cine Boulevard", 2, 440, "Privada"),
        ("Cine Gran Libertad", "Entre Ríos", "Federacion", "Chajarí", "3 De febrero 3060", "", 1, 400, "Privada"),
        ("Starlight Cinema Digital", "Entre Ríos", "Colon", "Colón", "Calle 12 De Abril 287", "https://www.facebook.com/StarlightCineColon/", 2, 154, "Privada"),
        ("Cine Teatro San Martin", "Entre Ríos", "Uruguay", "Concepción del Uruguay", "Estrada 820", "https://www.facebook.com/cinesanmartin/", 1, 457, "Privada"),
        ("Teatro Gran Odeon", "Entre Ríos", "Concordia", "Concordia", "Entre Rios 567", "http://www.fundacionodeon.com.ar", 1, 664, "Privada"),
        ("Altos Del Gualeguay", "Entre Ríos", "Gualeguay", "Gualeguay", "Rocamora 33", "https://www.facebook.com/pg/CineAltosDeGualeguay", 1, 198, "Privada"),
        ("Cinema Gualeguaychu", "Entre Ríos", "Gualeguaychu", "Gualeguaychú", "25 De mayo 1383", "http://cinemagualeguaychu.com", 1, 330, "Privada"),
        ("Cine Circulo Obrero", "Entre Ríos", "Parana", "Paraná", "Andres Pazos 339", "https://www.cinecirculo.com.ar/", 2, 300, "Privada"),
        ("Cine Urquiza", "Entre Ríos", "Colon", "San José", "25 De mayo 1849", "http://www.cineurquiza.com.ar", 1, 250, "Privada"),
        ("Sala Municipal Cine Teatro Victoria", "Entre Ríos", "Victoria", "Victoria", "Alem 64", "", 1, 299, "Pública"),
        ("Cine Teatro Berisso", "Entre Ríos", "Villaguay", "Villaguay", "San Martin 540", "https://www.facebook.com/pg/CineBerisso/", 1, 350, "Privada"),
        ("El Pajarito Avenida", "Formosa", "Formosa", "Formosa", "Av. Juan Domingo Peron 757", "https://www.facebook.com/Cines-Avenida-112830095434025/", 3, 619, "Privada"),
        ("Cine Teatro Altos Hornos Zapla", "Jujuy", "Palpala", "Palpala", "Av. Rio De La Plata 383", "https://www.facebook.com/pg/CineAHZ", 1, 1100, "Privada"),
        ("Cine Auditorium", "Jujuy", "Dr. Manuel Belgrano", "San Salvador de Jujuy", "Independencia Esq. Italia S/N", "https://www.facebook.com/CineAuditoriumJujuyINCAAMercosur/", 1, 201, ""),
        ("Cine Teatro Alfa", "Jujuy", "Dr. Manuel Belgrano", "San Salvador de Jujuy", "Patricias Argentinas 360", "https://twitter.com/cineteatroalfa", 2, 856, "Privada"),
        ("Barbarita Cruz", "Jujuy", "Tilcara", "Tilcara", "Belgrano 547", "https://capectilcara.com/", 1, 120, "Privada"),
        ("Espacio Incaa-Cine & Teatro Pico", "La Pampa", "Maraco", "Gral. Pico", "Calle 17 957", "http://www.picocine.com.ar/", 1, 534, "Privada"),
        ("Gran Pampa", "La Pampa", "Maraco", "Gral. Pico", "Calle 20 642", "", 1, 730, "Privada"),
        ("Amadeus", "La Pampa", "Capital", "Santa Rosa", "Coronel Gil 31", " www.cineamadeus.com.ar/", 1, 223, "Privada"),
        ("Milenium", "La Pampa", "Capital", "Santa Rosa", "Escalante 270", "", 1, 352, "Privada"),
        ("Sala Auditorio Juan C. Bustriazo Ortiz", "La Pampa", "Capital", "Santa Rosa", "Quintana 172", "Facebook: Espacio INCAA Santa Rosa", 1, 118, "Pública"),
        ("Cine El Progreso", "La Rioja", "Arauco", "Aimogasta", "9 De julio 85", "", 1, 285, ""),
        ("Cinema 3D Chilecito", "La Rioja", "Chilecito", "Chilecito", "La Plata y 19 De Febrero", "http://cinema3dlarioja.com/", 2, 216, "Privada"),
        ("Cinema 3D Pelagio B. Luna", "La Rioja", "Capital", "La Rioja", "Pelagio Luna 960", "http://cinema3dlarioja.com/", 2, 292, "Privada"),
        ("Cinema 3D San Martin", "La Rioja", "Capital", "La Rioja", "San Martin 62", "http://cinema3dlarioja.com/", 1, 72, "Privada"),
        ("Cinemacenter La Rioja", "La Rioja", "Capital", "La Rioja", "Av. Abel Bazan Y Bustos 710", "http://www.cinemacenter.com.ar/", 4, 769, "Privada"),
        ("Espacio 73", "La Rioja", "Capital", "La Rioja", "Catamarca 73", "http://www.culturalarioja.gob.ar", 1, 128, "Pública"),
        ("Cineteatro Antonio Lafalla", "Mendoza", "General Alvear", "General Alvear", "Av. Alvear Oeste 437", "https://cineteatrolafalla.alvearmendoza.gob.ar/", 1, 122, "Pública"),
        ("Cinemark Palmares", "Mendoza", "Godoy Cruz", "Godoy Cruz", "Ruta Panamericana 2650", "https://www.cinemarkhoyts.com.ar", 10, 1681, "Privada"),
        ("Tadicor Las Heras", "Mendoza", "Las Heras", "Las Heras", "Juan Dragui Lucero 1450", "http://www.tadicor.com/Cines.php", 2, 284, "Privada"),
        ("Cine Teatro Imperial", "Mendoza", "Maipu", "Maipú", "Pablo Pescara Y Peron", "https://www.facebook.com/pg/Cineteatroimperial/", 1, 600, "Privada"),
        ("Cinepolis Arena Maipu", "Mendoza", "Maipu", "Maipú", "Emilio Civit Y Maza", "https://www.villagecines.com/", 5, 949, "Privada"),
        ("Sala Maiten", "Mendoza", "Malargue", "Malargüe", "Ruta 40 Norte Y Pje Orteguina", "https://www.malargue.gov.ar/", 1, 160, "Pública"),
        ("Cine Universidad", "Mendoza", "Capital", "Mendoza", "Juan Agustín Maza 250", "http://cine.uncuyo.edu.ar/", 2, 350, "Pública"),
        ("Cinemacenter Mendoza", "Mendoza", "Capital", "Mendoza", "Las Cañas 1833", "http://www.cinemacenter.com.ar/", 6, 1361, "Privada"),
        ("Cinepolis Mendoza", "Mendoza", "Capital", "Mendoza", "Av. Acceso Este 3280 Lateral Norte", "https://www.villagecines.com/", 10, 2344, "Privada"),
        ("Microcine Municipal David Eisenchlas", "Mendoza", "Capital", "Mendoza", "9 De julio 0500", "", 1, 115, "Pública"),
        ("Porky`S", "Mendoza", "Capital", "Mendoza", "Lavalle 32", "", 1, 70, "Privada"),
        ("Centro Cultural Juan Centorbi", "Mendoza", "Rivadavia", "Rivadavia", "Lavalle 740", "", 1, 963, "Pública"),
        ("Cine Cervantes San Martin", "Mendoza", "San Martin", "San Martín", "9 De julio 0187", "http://www.cinecervantes.com", 1, 328, "Privada"),
        ("Tadicor San Martin", "Mendoza", "San Martin", "San Martín", "Lateral Sur Ruta Nacional 7 Sin Nro", "htpp:/www.tadicor.com sección cines", 2, 302, "Privada"),
        ("Centro Cultural San Rafael del Diamante", "Mendoza", "San Rafael", "San Rafael", "Av. Hipolito Yrigoyen 280", "https://www.facebook.com/TeatroRomaSanRafael", 1, 690, "Pública"),
        ("Cine Amelix", "Mendoza", "San Rafael", "San Rafael", "San Martin 139", "https://www.facebook.com/CineAmelix/", 2, 359, "Privada"),
        ("Cinema Américo", "Mendoza", "Tupungato", "Tupungato", "La Gloria 1777", "https://www.facebook.com/Cinemaamericotupungatomendoza", 1, 113, "Privada"),
        ("Cine Teatro Obera", "Misiones", "Obera", "Oberá", "San Martin 1069", "https://www.facebook.com/CineTeatroObera/", 1, 220, "Pública"),
        ("Microcines Obera", "Misiones", "Obera", "Oberá", "Av. Sarmiento 1044", "www.cinescasinoobera.com.ar/", 2, 292, "Privada"),
        ("Imax Del Conocimiento", "Misiones", "Capital", "Posadas", "Ruta 12 Y Acceso Oeste (Av. Ulises Lopez)", "https://www.parquedelconocimiento.com/", 1, 546, "Pública"),
        ("Sunstar Posadas", "Misiones", "Capital", "Posadas", "Bolivar 1979", "http://www.cinesunstar.com/", 4, 559, "Privada"),
        ("Cinemark Neuquén", "Neuquén", "Confluencia", "Neuquén", "Av. Dr. Ramón 355", "https://www.cinemarkhoyts.com.ar/", 6, 1113, "Privada"),
        ("Auditorio Casa de la Cultura", "Neuquén", "Pehuenches", "Rincón de Los Sauces", "Perón y 20 de Diciembre", "Facebook: Cine Casa de la Cultura Rincón de los Sauces", 1, 98, "Pública"),
        ("Cine Rex Cutral Co", "Neuquén", "Confluencia", "Cutral-Co", "Av. Del Trabajo 676", "http://www.cinerexcutralco.com.ar", 1, 290, "Privada"),
        ("Cine Teatro Español", "Neuquén", "Confluencia", "Neuquén", "Av. Argentina 245", "https://www.facebook.com/cineteatronqn/", 1, 639, "Privada"),
        ("Cinepolis Neuquen", "Neuquén", "Confluencia", "Neuquén", "Av. Antartida Argentina 1111", "https://www.villagecines.com/", 7, 1894, "Privada"),
        ("Centro Cultural Cotesma", "Neuquén", "Lacar", "San Martín de los Andes", "Gral. Roca 1154", "http://centrocultural.cotesma.com.ar", 2, 398, "Privada"),
        ("Cine Teatro Municipal Amado Sapag", "Neuquén", "Zapala", "Zapala", "San Martin 281", "Facebook: Cine Teatro de Zapala", 1, 738, "Pública"),
        ("Lorenzo Kelly", "Río Negro", "General Roca", "Cipolletti", "Fernandez Oro 55", "https://ccc.cipolletti.gob.ar/", 1, 140, "Pública"),
        ("Sunstar Bariloche", "Río Negro", "Bariloche", "Bariloche", "Onelli 447", "http://www.cinesunstar.com/", 3, 461, "Privada"),
        ("Cine Teatro Español", "Río Negro", "General Roca", "Cinco Saltos", "Av. Roca 326", "https://www.facebook.com/cineespanolCS/", 1, 320, "Privada"),
        ("Cine Rex Gral. Roca", "Río Negro", "General Roca", "Gral. Roca", "Av. Roca 1585", "http://cinerexroca.com.ar", 2, 300, "Privada"),
        ("Cine Rex Viedma", "Río Negro", "Adolfo Alsina", "Viedma", "Gallardo 160", "https://cines.com/argentina/cine-gama/", 1, 350, "Privada"),
        ("Cine Teatro Circulo Italiano", "Río Negro", "General Roca", "Villa Regina", "Av. Rivadavia 117", "http://cineteatrocirculo.com.ar/", 1, 661, "Privada"),
        ("Cine Municipal De La Cultura Oran", "Salta", "Oran", "Orán", "Hipolito Yrigoyen 137", "", 1, 280, "Pública"),
        ("Cine Opera", "Salta", "Capital", "Salta", "Urquiza 560", "http://cineoperasalta.com.ar/", 2, 682, "Privada"),
        ("Cine Rex", "Salta", "Capital", "Salta", "Av. San Martin 1170", "", 2, 353, "Privada"),
        ("Cinemark Salta", "Salta", "Capital", "Salta", "Av. Monseñor Tavella 4400", "https://www.cinemarkhoyts.com.ar", 5, 897, "Privada"),
        ("Hoyts Nuevo Noa", "Salta", "Capital", "Salta", "Virrey Toledo 702", "https://www.cinemarkhoyts.com.ar/", 8, 1362, "Privada"),
        ("Cine Club Center", "Salta", "Metán", "San José de Metán", "20 De febrero 19", "https://www.facebook.com/cinecentermetan/", 1, 80, "Privada"),
        ("Open Plaza", "Salta", "Grl. Jose de San Martin", "Tartagal", "Guemes 421", "http://www.cineopenplaza.com.ar", 1, 220, "Privada"),
        ("Cinemacenter San Juan", "San Juan", "Capital", "San Juan", "Av. Circunvalacion Y Scalabrini Ortiz", "http://www.cinemacenter.com.ar/", 8, 1803, "Privada"),
        ("CPM Espacio San Juan", "San Juan", "Capital", "San Juan", "Av. Jose Ignacio De La Roza Oeste 806", "https://cpmcines.com/", 5, 849, "Privada"),
        ("Play Cinema San Juan", "San Juan", "Capital", "San Juan", "Av. Libertador 1826 (Oeste)", "http://www.playcinema.net/", 6, 1071, "Privada"),
        ("UPCN - San Juan", "San Juan", "Capital", "San Juan", "Sarmiento 461 Sur", "http://www.upcndigital.org/san-juan", 1, 298, "Privada"),
        ("Cine Star Merlo", "San Luis", "Junin", "Merlo", "Av. Del Sol 1120", "https://www.facebook.com/CineStarMerlo/", 1, 100, "Privada"),
        ("Cinemacenter San Luis", "San Luis", "La Capital", "San Luis", "J. A. Roca 260", "http://www.cinemacenter.com.ar/", 7, 1951, "Privada"),
        ("Cines Fenix", "San Luis", "General Pedernera", "Villa Mercedes", "Pueyrredon 1651", "http://www.cinesfenix.com", 3, 475, "Privada"),
        ("Cine Municipal Caleta Olivia", "Santa Cruz", "Deseado", "Caleta Olivia", "J. Newbery y Deocarets S/N", "https://www.mechenien.org.ar/", 1, 350, "Privada"),
        ("Cine Select", "Santa Cruz", "Corpen Aike", "Comandante Luis Piedrabuena", "Av. Gregorio Ibañez 388", "https://www.facebook.com/multiespacioselect", 1, 288, "Pública"),
        ("Cine Municipal Abuelas de Plaza de Mayo", "Santa Cruz", "Rio Chico", "Gobernador Gregores", "Av. San Martin 514", "http://www.santacruz.gob.ar", 1, 80, "Pública"),
        ("Osvaldo Jorge Bayer", "Santa Cruz", "Las Heras", "Las Heras", "13 De Diciembre Y Malvinas S/N", "https://www.facebook.com/pg/centroculturallasheras", 1, 196, "Privada"),
        ("Cine Auditorio Deseado ESPACIO INCAA", "Santa Cruz", "Deseado", "Puerto Deseado", "Don Bosco 1075", "https://www.facebook.com/CineDeseado/", 1, 142, "Privada"),
        ("Cine Teatro Talia", "Santa Cruz", "Magallanes", "Puerto San Julian", "25 De mayo 1188", "https://www.facebook.com/pg/cineteatrotalia", 1, 340, "Privada"),
        ("Auditorio Municipal", "Santa Cruz", "Corpen Aike", "Puerto Santa Cruz", "25 De mayo 0513", "https://www.facebook.com/CineMPSC/", 1, 150, "Pública"),
        ("Cine Rio Gallegos", "Santa Cruz", "Guer Aike", "Río Gallegos", "Av. Nestor Kirchner 1142", "http://www.cineriogallegos.com.ar/", 3, 290, "Privada"),
        ("Luna De Avellaneda", "Santa Fe", "General Obligado", "Avellaneda", "Av. San Martin 810", "http://www.cinelunadeavellaneda.com", 1, 299, "Privada"),
        ("Cine Teatro Libertador", "Santa Fe", "Caseros", "Casilda", "Buenos Aires 2441", "http://www.cinelibertador.com.ar", 1, 1014, "Privada"),
        ("E-Max Cines", "Santa Fe", "Las Colonias", "Esperanza", "Brigadier Lopez 1471", "http://www.e-max.com.ar", 3, 584, "Privada"),
        ("Cine Teatro Municipal Manuel Belgrano", "Santa Fe", "Castellanos", "Rafaela", "Bv. Santa Fe 555", "http://www.rafaela.gob.ar/cine/", 1, 1049, "Pública"),
        ("Las Tipas Rafaela", "Santa Fe", "Castellanos", "Rafaela", "C. Conscripto Zurbriggen 865", "www.lastipasrafaela.com.ar/", 4, 920, "Privada"),
        ("Cine Recite", "Santa Fe", "General Obligado", "Reconquista", "Habegger 755", "http://www.cinerecite.com.ar", 1, 156, "Privada"),
        ("Arteon", "Santa Fe", "Rosario", "Rosario", "Sarmiento 778", "http://www.arteon.com.ar/", 1, 186, "Privada"),
        ("Centro Cultural Cine Lumiere", "Santa Fe", "Rosario", "Rosario", "Velez Sarfield 1029", "http://www.lumiererosario.gob.ar", 1, 420, "Pública"),
        ("Cinepolis Rosario", "Santa Fe", "Rosario", "Rosario", "Eva Peron 5856", "https://www.villagecines.com/", 13, 3458, "Privada"),
        ("Cines Del Centro", "Santa Fe", "Rosario", "Rosario", "Rioja 1660", "", 4, 659, "Privada"),
        ("El Cairo", "Santa Fe", "Rosario", "Rosario", "Santa Fe 1120", "http://elcairocinepublico.gob.ar/", 1, 442, "Pública"),
        ("Hoyts Rosario", "Santa Fe", "Rosario", "Rosario", "Nansen 323", "https://www.cinemarkhoyts.com.ar/", 9, 1911, "Privada"),
        ("Microcine De La Cortada", "Santa Fe", "Rosario", "Rosario", "Ctda Ricardone 1244", "", 1, 96, "Privada"),
        ("Monumental Rosario", "Santa Fe", "Rosario", "Rosario", "San Martin 993", "https://www.multiplex.com.ar/", 9, 1471, "Privada"),
        ("Showcase Rosario", "Santa Fe", "Rosario", "Rosario", "Junin 501", "https://www.todoshowcase.com/", 14, 3391, "Privada"),
        ("Sala Hispano", "Santa Fe", "General Lopez", "Rufino", "Av. Cobo 185", "", 1, 330, "Pública"),
        ("Las Tipas San Jorge", "Santa Fe", "San Martin", "San Jorge", "Eva Peron 1388", "http://www.lastipassanjorge.com.ar/", 1, 260, "Privada"),
        ("Brown Cinema 3D", "Santa Fe", "Castellanos", "San Vicente", "Cangallo 304", "http://browncinema3d.com.ar/", 1, 224, "Privada"),
        ("Cine America", "Santa Fe", "La Capital", "Santa Fe", "25 De mayo 3075", "", 1, 380, "Privada"),
        ("Cinemark Santa Fe", "Santa Fe", "La Capital", "Santa Fe", "Dique 1 Puerto Santa Fe", "https://www.cinemarkhoyts.com.ar", 7, 1527, "Privada"),
        ("Cinema Casey", "Santa Fe", "General Lopez", "Venado Tuerto", "Av. Casey 790", "http://cinemacasey.com.ar", 2, 249, "Privada"),
        ("Cine Teatro Municipal Renzi", "Santiago del Estero", "Banda", "La Banda", "Av. Besares 151", "https://www.facebook.com/CineRenzi/", 1, 152, "Pública"),
        ("Cinemacenter La Banda", "Santiago del Estero", "Banda", "La Banda", "Aut. Juan D. Peron S/N Parque Industrial", "http://www.cinemacenter.com.ar/", 3, 822, "Privada"),
        ("Sunstar Santiago del Estero", "Santiago del Estero", "Capital", "Santiago del Estero", "Av. Rivadavia Y Ejercito Argentino", "http://www.cinesunstar.com/", 5, 1585, "Privada"),
        ("Nuevo Cine Rex", "Santiago del Estero", "Rio Hondo", "Termas de Río Hondo", "Bolivar 15", "http://www.santacruz.gob.ar", 1, 233, "Privada"),
        ("El Cine", "Tierra del Fuego", "Rio Grande", "Río Grande", "9 De julio 0838", "http://www.cinemas4riogrande.com.ar", 2, 584, "Privada"),
        ("Cine Teatro Pakewaia", "Tierra del Fuego", "Ushuaia", "Ushuaia", "Yaganes Y Gob Paz (Base Naval)", "www.cinepackewaia.com.ar/", 1, 300, "Privada"),
        ("Sunstar Ushuaia", "Tierra del Fuego", "Ushuaia", "Ushuaia", "Av. Perito Moreno 1460", "http://www.cinesunstar.com/", 3, 561, "Privada"),
        ("Atlas Vía 24", "Tucumán", "Capital", "San Miguel de Tucumán", "24 de septiembre 0757", "https://www.cineatlasweb.com.ar/", 2, 264, "Privada"),
        ("Cine Popular San Miguel de Tucumán", "Tucumán", "Capital", "San Miguel de Tucumán", "Lavalle 688", "", 1, 50, "Privada"),
        ("Sala Hynes O´Connor", "Tucumán", "Capital", "San Miguel de Tucumán", "San Martín 251", "", 1, 80, "Pública"),
        ("Cine Popular de Yerba Buena", "Tucumán", "Yerba Buena", "Yerba Buena", "Av. Aconquija 2060", "", 1, 50, "Privada"),
        ("Atlas Shopping Terminal", "Tucumán", "Capital", "San Miguel de Tucumán", "Av. Brigido Teran 250", "cineatlasweb.com.ar", 2, 219, "Privada"),
        ("Atlas Tucuman", "Tucumán", "Capital", "San Miguel de Tucumán", "Monteagudo 250", "cineatlasweb.com.ar", 3, 797, "Privada"),
        ("Cinemacenter Tucuman", "Tucumán", "Capital", "San Miguel de Tucumán", "Av. Nestor Kirchner(Ex Av. Roca) 3450", "http://www.cinemacenter.com.ar/", 5, 1051, "Privada"),
        ("Espacio Incaa Sala Orestes Caviglia", "Tucumán", "Capital", "San Miguel de Tucumán", "San Martin 251", "https://enteculturaltucuman.gob.ar/", 1, 183, "Pública"),
        ("Microcine Orion", "Tucumán", "Capital", "San Miguel de Tucumán", "Av. Mitre 817", "", 1, 36, "Pública"),
        ("Solar del Cerro", "Tucumán", "Yerba Buena", "Yerba Buena", "Av. Aconquija 1336", "http://solardelcerro.com", 5, 750, "Privada"),
        ("Sunstar Tucuman", "Tucumán", "Yerba Buena", "Yerba Buena", "Av. Fermin Carriola 42", "http://www.cinesunstar.com/", 6, 1295, "Privada")]

